version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 300mb
    container_name: postgres-nodejs
    environment:
      POSTGRES_PASSWORD: pas123
      POSTGRES_DB: library
      POSTGRES_USER: library
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    restart: always
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgresql://library:pas123@db:5432/library
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  pgdata:
